# ActiveMQ Configuration
spring.activemq.broker-url=tcp://127.0.0.1:61616
spring.activemq.user=admin
spring.activemq.password=admin

# JMS Configuration
spring.jms.pub-sub-domain=false
spring.jms.template.default-destination=myQueue

# Connection Pool
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=10

# Enable JMS
spring.jms.listener.auto-startup=true

spring.main.allow-circular-references=true
spring.main.web-application-type=reactive	

# Logging
logging.level.org.springframework.jms=DEBUG
logging.level.org.apache.activemq=DEBUG

logging.level.org.springframework=DEBUG
logging.level.org.springframework.boot.autoconfigure=DEBUG
logging.level.org.springframework.context=DEBUG
logging.level.com.esdrasdemorais.drones=DEBUG
